// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYGuXHG0JRadhjSAAYlckavlwN9m7EC0',
    appId: '1:15669381434:web:8e344611a422b42e626803',
    messagingSenderId: '15669381434',
    projectId: 'locksphere-4e99b',
    authDomain: 'locksphere-4e99b.firebaseapp.com',
    storageBucket: 'locksphere-4e99b.firebasestorage.app',
    measurementId: 'G-00JYHTL4FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJcSUgGOfVT1y6NXPqRbewjg-u50YiWLg',
    appId: '1:15669381434:android:0b97d7d2be61bb45626803',
    messagingSenderId: '15669381434',
    projectId: 'locksphere-4e99b',
    storageBucket: 'locksphere-4e99b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5W5PHZE5B1bJWwrpAVeI4wSNWLjwKHU',
    appId: '1:15669381434:ios:a56dc3199f33f0cd626803',
    messagingSenderId: '15669381434',
    projectId: 'locksphere-4e99b',
    storageBucket: 'locksphere-4e99b.firebasestorage.app',
    iosBundleId: 'com.example.biometricAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5W5PHZE5B1bJWwrpAVeI4wSNWLjwKHU',
    appId: '1:15669381434:ios:a56dc3199f33f0cd626803',
    messagingSenderId: '15669381434',
    projectId: 'locksphere-4e99b',
    storageBucket: 'locksphere-4e99b.firebasestorage.app',
    iosBundleId: 'com.example.biometricAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkYGuXHG0JRadhjSAAYlckavlwN9m7EC0',
    appId: '1:15669381434:web:4d6172003ff0e048626803',
    messagingSenderId: '15669381434',
    projectId: 'locksphere-4e99b',
    authDomain: 'locksphere-4e99b.firebaseapp.com',
    storageBucket: 'locksphere-4e99b.firebasestorage.app',
    measurementId: 'G-5451LD3LZ4',
  );
}
